stages:
  data_ingestion:
    cmd: python src/context/pipeline/data_ingestion_pipeline.py
    deps:
      - src/context/pipeline/data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/images


  create_model:
      cmd: python src/context/pipeline/base_model_pipeline.py
      deps:
        - src/context/pipeline/base_model_pipeline.py
        - config/config.yaml
      params:
        - INPUT_SIZE
        - NUM_CLASSES
        - WEIGHTS
        - LEARNING_RATE
      outs:
        - artifacts/model

